// file: lib/k8s/jobsData.ts
const now = 1696950000; // epoch de exemplo apenas para ordenação mock

const jobs = [
  {
    id: "j1",
    name: "media-snapshot-2025-10-10-1130",
    namespace: "media",
    owner: "CronJob/media-snapshot",
    status: "Succeeded", // Active | Succeeded | Failed | Suspended
    completions: 1,
    parallelism: 1,
    succeeded: 1,
    failed: 0,
    active: 0,
    backoffLimit: 6,
    ttlSecondsAfterFinished: 3600,
    restartPolicy: "OnFailure",
    imageTag: "ghcr.io/synth/media-snapshot:1.3.0",
    startedAt: "10/10/2025 11:30",
    startedAtEpoch: now - 60 * 60,
    completedAt: "10/10/2025 11:32",
    durationSec: 120,
    age: "38m",
    selector: { job: "media-snapshot-2025-10-10-1130" },
    template: {
      labels: { job: "media-snapshot-2025-10-10-1130" },
      containers: [{ name: "snapshot", image: "ghcr.io/synth/media-snapshot:1.3.0" }],
    },
    pods: [
      { name: "media-snapshot-abc11", node: "ip-192-168-89-7", phase: "Succeeded", restarts: 0, age: "36m" },
    ],
    conditions: [
      { type: "Complete", status: "True", lastUpdate: "10/10/2025 11:32", lastTransition: "10/10/2025 11:32", reason: "Completed", message: "Job completed successfully." },
    ],
    events: [
      { id: "e1", type: "Normal", reason: "Completed", message: "Job completed", object: "Job/media-snapshot-...", age: "36m" },
    ],
  },
  {
    id: "j2",
    name: "video-extract-frames-44",
    namespace: "media",
    owner: "Deployment/media-proc",
    status: "Active",
    completions: 10,
    parallelism: 3,
    succeeded: 6,
    failed: 1,
    active: 3,
    backoffLimit: 4,
    restartPolicy: "OnFailure",
    imageTag: "ghcr.io/synth/video-extract:0.9.1",
    startedAt: "10/10/2025 11:20",
    startedAtEpoch: now - 60 * 80,
    completedAt: null,
    durationSec: 80 * 60,
    age: "48m",
    selector: { job: "video-extract-frames-44" },
    template: {
      labels: { job: "video-extract-frames-44" },
      containers: [{ name: "extractor", image: "ghcr.io/synth/video-extract:0.9.1" }],
    },
    pods: [
      { name: "video-extract-44-a1", node: "ip-192-168-88-5", phase: "Running", restarts: 0, age: "45m" },
      { name: "video-extract-44-b2", node: "ip-192-168-87-11", phase: "Running", restarts: 1, age: "44m" },
      { name: "video-extract-44-c3", node: "ip-192-168-89-7", phase: "Running", restarts: 0, age: "42m" },
    ],
    conditions: [
      { type: "Complete", status: "False", lastUpdate: "10/10/2025 11:40", lastTransition: "10/10/2025 11:40", reason: "StillRunning", message: "Some pods are still running." },
    ],
    events: [
      { id: "e2", type: "Normal", reason: "Pulled", message: "Successfully pulled image", object: "Pod/video-extract-44-a1", age: "46m" },
    ],
  },
  {
    id: "j3",
    name: "db-backup-2025-10-10-1100",
    namespace: "db",
    owner: "CronJob/db-backup",
    status: "Failed",
    completions: 1,
    parallelism: 1,
    succeeded: 0,
    failed: 1,
    active: 0,
    backoffLimit: 3,
    ttlSecondsAfterFinished: 7200,
    restartPolicy: "OnFailure",
    imageTag: "ghcr.io/synth/db-backup:2.2.1",
    startedAt: "10/10/2025 11:00",
    startedAtEpoch: now - 60 * 120,
    completedAt: "10/10/2025 11:08",
    durationSec: 480,
    age: "1h 8m",
    selector: { job: "db-backup-2025-10-10-1100" },
    template: {
      labels: { job: "db-backup-2025-10-10-1100" },
      containers: [{ name: "backup", image: "ghcr.io/synth/db-backup:2.2.1" }],
    },
    pods: [
      { name: "db-backup-1100-x1", node: "ip-192-168-89-7", phase: "Failed", restarts: 2, age: "1h 5m" },
    ],
    conditions: [
      { type: "Failed", status: "True", lastUpdate: "10/10/2025 11:08", lastTransition: "10/10/2025 11:08", reason: "ExitCode1", message: "Backup script failed." },
    ],
    events: [
      { id: "e3", type: "Warning", reason: "BackOff", message: "Back-off restarting failed container", object: "Pod/db-backup-1100-x1", age: "1h 6m" },
    ],
  },
  {
    id: "j4",
    name: "img-thumbnail-batch",
    namespace: "web",
    owner: "Manual",
    status: "Suspended",
    completions: 5,
    parallelism: 2,
    succeeded: 0,
    failed: 0,
    active: 0,
    backoffLimit: 6,
    restartPolicy: "Never",
    imageTag: "ghcr.io/synth/img-thumb:1.0.0",
    startedAt: "-",
    startedAtEpoch: 0,
    completedAt: null,
    durationSec: 0,
    age: "—",
    selector: { job: "img-thumbnail-batch" },
    template: {
      labels: { job: "img-thumbnail-batch" },
      containers: [{ name: "thumb", image: "ghcr.io/synth/img-thumb:1.0.0" }],
    },
    pods: [],
    conditions: [],
    events: [],
  },
];

export default jobs;
