// file: lib/k8s/storageData.ts
export const pvs = [
  {
    id: "pv1",
    name: "pv-media-001",
    storageClass: "gp3-retain",
    capacityGi: 200,
    accessModes: ["ReadWriteOnce"],
    reclaimPolicy: "Retain",
    volumeMode: "Filesystem",
    provisioner: "ebs.csi.aws.com",
    phase: "Bound",
    claim: { namespace: "media", name: "pvc-media-data" },
    node: null,
    age: "2d",
    ageSec: 172800,
    events: [
      { id: "e1", type: "Normal", reason: "Bound", message: "Bound to pvc/media/pvc-media-data", age: "2d" },
    ],
  },
  {
    id: "pv2",
    name: "pv-db-logs",
    storageClass: "gp3-delete",
    capacityGi: 100,
    accessModes: ["ReadWriteOnce"],
    reclaimPolicy: "Delete",
    volumeMode: "Filesystem",
    provisioner: "ebs.csi.aws.com",
    phase: "Available",
    claim: null,
    node: null,
    age: "6h",
    ageSec: 21600,
    events: [],
  },
  {
    id: "pv3",
    name: "local-scratch-01",
    storageClass: null,
    capacityGi: 50,
    accessModes: ["ReadWriteOnce"],
    reclaimPolicy: "Delete",
    volumeMode: "Block",
    provisioner: null,
    phase: "Released",
    claim: { namespace: "api", name: "pvc-api-scratch" },
    node: "ip-192-168-88-5",
    age: "1d",
    ageSec: 86400,
    events: [
      { id: "e2", type: "Warning", reason: "Released", message: "PVC deleted, PV needs recycling", age: "1d" },
    ],
  },
];

export const pvcs = [
  {
    id: "pvc1",
    name: "pvc-media-data",
    namespace: "media",
    storageClass: "gp3-retain",
    requestGi: 200,
    usedGi: 143, // mock
    accessModes: ["ReadWriteOnce"],
    phase: "Bound",
    volume: "pv-media-001",
    selector: {},
    age: "2d",
    ageSec: 172800,
    events: [],
  },
  {
    id: "pvc2",
    name: "pvc-db-backups",
    namespace: "db",
    storageClass: "gp3-delete",
    requestGi: 300,
    usedGi: 22,
    accessModes: ["ReadWriteOnce"],
    phase: "Pending",
    volume: null,
    selector: { app: "backup" },
    age: "30m",
    ageSec: 1800,
    events: [
      { id: "e3", type: "Warning", reason: "ProvisioningFailed", message: "No space left on storageclass", age: "28m" },
    ],
  },
  {
    id: "pvc3",
    name: "pvc-api-scratch",
    namespace: "api",
    storageClass: null,
    requestGi: 10,
    usedGi: 0,
    accessModes: ["ReadWriteOnce"],
    phase: "Lost",
    volume: null,
    selector: {},
    age: "3h",
    ageSec: 10800,
    events: [
      { id: "e4", type: "Warning", reason: "Lost", message: "Underlying volume released", age: "2h" },
    ],
  },
];

export const scs = [
  {
    id: "sc1",
    name: "gp3-retain",
    provisioner: "ebs.csi.aws.com",
    reclaimPolicy: "Retain",
    allowExpansion: true,
    parameters: { type: "gp3", iops: "3000", encrypted: "true" },
    age: "90d",
    ageSec: 7776000,
  },
  {
    id: "sc2",
    name: "gp3-delete",
    provisioner: "ebs.csi.aws.com",
    reclaimPolicy: "Delete",
    allowExpansion: true,
    parameters: { type: "gp3", encrypted: "true" },
    age: "120d",
    ageSec: 10368000,
  },
  {
    id: "sc3",
    name: "local-path",
    provisioner: "k8s.io/minikube-hostpath",
    reclaimPolicy: "Delete",
    allowExpansion: false,
    parameters: {},
    age: "300d",
    ageSec: 25920000,
  },
];
