export const servicesSeed = [
  {
    id: "svc-1",
    name: "web-api",
    env: "prod",
    status: "UP",
    latency: 182,
    owner: "Tribo Checkout",
    tags: ["core", "edge", "canary"],
    lastDeploy: "há 8 min",
    version: "v2.18.4",
    uptime: "99.92%",
    replicas: 14,
    region: "us-east-1",
  },
  {
    id: "svc-2",
    name: "checkout",
    env: "prod",
    status: "DEGRADED",
    latency: 245,
    owner: "Tribo Checkout",
    tags: ["payments", "pci"],
    lastDeploy: "há 22 min",
    version: "v3.2.1",
    uptime: "99.51%",
    replicas: 10,
    region: "us-east-1",
  },
  {
    id: "svc-3",
    name: "auth",
    env: "prod",
    status: "UP",
    latency: 110,
    owner: "Platform",
    tags: ["critical", "edge"],
    lastDeploy: "há 2 h",
    version: "v1.8.0",
    uptime: "99.99%",
    replicas: 8,
    region: "eu-west-1",
  },
  {
    id: "svc-4",
    name: "notifications",
    env: "stage",
    status: "UP",
    latency: 164,
    owner: "Growth",
    tags: ["async"],
    lastDeploy: "há 40 min",
    version: "v1.4.3",
    uptime: "99.9%",
    replicas: 4,
    region: "us-east-1",
  },
  {
    id: "svc-5",
    name: "catalog",
    env: "stage",
    status: "UP",
    latency: 174,
    owner: "Platform",
    tags: ["search"],
    lastDeploy: "há 35 min",
    version: "v1.9.0",
    uptime: "99.85%",
    replicas: 6,
    region: "us-east-2",
  },
  {
    id: "svc-6",
    name: "worker-billing",
    env: "prod",
    status: "UP",
    latency: 138,
    owner: "FinOps",
    tags: ["queues", "billing"],
    lastDeploy: "há 12 min",
    version: "v1.4.7",
    uptime: "99.77%",
    replicas: 5,
    region: "sa-east-1",
  },
  {
    id: "svc-7",
    name: "fraud-detector",
    env: "dev",
    status: "DOWN",
    latency: 0,
    owner: "Risk",
    tags: ["ml", "pci"],
    lastDeploy: "há 1 d",
    version: "v0.9.2",
    uptime: "97.4%",
    replicas: 2,
    region: "us-west-2",
  },
  {
    id: "svc-8",
    name: "search-api",
    env: "prod",
    status: "UP",
    latency: 156,
    owner: "Platform",
    tags: ["core"],
    lastDeploy: "há 55 min",
    version: "v2.3.1",
    uptime: "99.8%",
    replicas: 9,
    region: "us-west-1",
  },
];
